# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RandomMatrixCpp <- function(dim, max_value) {
    .Call('GibbsRF_RandomMatrixCpp', PACKAGE = 'GibbsRF', dim, max_value)
}

ConditionalProbs <- function(X, position, max_value, cMat, vMat, V) {
    .Call('GibbsRF_ConditionalProbs', PACKAGE = 'GibbsRF', X, position, max_value, cMat, vMat, V)
}

rGRF <- function(cMat, vMat, V, max_value, macrosteps, initial) {
    .Call('GibbsRF_rGRF', PACKAGE = 'GibbsRF', cMat, vMat, V, max_value, macrosteps, initial)
}

log_plik <- function(X, cMat, vMat, V, max_value) {
    .Call('GibbsRF_log_plik', PACKAGE = 'GibbsRF', X, cMat, vMat, V, max_value)
}

